Resources:
  ProfileImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:provider.environment.PROFILE_IMAGES_BUCKET}
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: [GET, PUT, POST, DELETE]
            AllowedOrigins: ["*"]
            MaxAge: 3000
